env:
  es2020: true
  node: true
extends:
  - google
  #- eslint:recommended
  #- plugin:@typescript-eslint/eslint-recommended
  #- plugin:@typescript-eslint/recommended
  #- plugin:prettier/recommended
  #- prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  #project: ./tsconfig.json #いらん？
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars': off
  'no-unused-vars': off
  #'no-extra-semi'
  #'quotes': ['error', 'single']
  #'semi':
    #- error
    #- always
  #'@typescript-eslint/no-var-requires': on
  

